<?php
require_once('../tcpdf/tcpdf.php');
include '../db.php';

if (!isset($_GET['patient_id'])) {
    die('Patient ID required.');
}

$patient_id = $_GET['patient_id'];

// Fetch patient details
$patientStmt = $pdo->prepare("SELECT full_name FROM patients WHERE patient_id = ?");
$patientStmt->execute([$patient_id]);
$patient = $patientStmt->fetch();

if (!$patient) {
    die('Invalid patient.');
}

$patient_name = htmlspecialchars($patient['full_name']);
$currentDate = date('Y-m-d H:i');

// Fetch only new/unprinted bills
$stmt = $pdo->prepare("SELECT s.service_name, s.cost, b.quantity, (s.cost * b.quantity) AS total
                       FROM hos_bills b
                       JOIN bill_services s ON b.service_id = s.id
                       WHERE b.patient_id = ? AND b.printed = 0");
$stmt->execute([$patient_id]);
$rows = $stmt->fetchAll();

if (!$rows) {
    die("<h3>No new bills to print for {$patient_name}.</h3>");
}

// Initialize PDF
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Hospital System');
$pdf->SetTitle('Invoice - ' . $patient_name);
$pdf->SetMargins(15, 20, 15);
$pdf->SetAutoPageBreak(TRUE, 20);
$pdf->AddPage();
$pdf->SetFont('dejavusans', '', 11);

// Start HTML content
$grandTotal = 0;

$html = <<<EOD
<style>
    h2 { text-align: center; color: #2c3e50; background-color: #ecf0f1; padding: 8px; border-radius: 6px; }
    .info { background-color: #f7f7f7; padding: 10px; border: 1px solid #ccc; margin-bottom: 15px; font-size: 12pt; }
    table { border-collapse: collapse; width: 100%; font-size: 11pt; }
    th { background-color: #3498db; color: white; border: 1px solid #2980b9; padding: 8px; text-align: center; }
    td { border: 1px solid #ccc; padding: 8px; }
    tr:nth-child(even) { background-color: #f9f9f9; }
    .total-row td { font-weight: bold; background-color: #dff0d8; border-top: 2px solid #2c3e50; }
    .footer { margin-top: 30px; text-align: right; font-style: italic; font-size: 10pt; color: #555; }
</style>

<h2>Angelora Hospital Invoice</h2>
<div class="info">
    <strong>Patient Name:</strong> $patient_name<br>
    <strong>Date:</strong> $currentDate
</div>

<table>
<thead>
<tr>
    <th>Service</th>
    <th>Cost (₦)</th>
    <th>Qty</th>
    <th>Total (₦)</th>
</tr>
</thead>
<tbody>
EOD;

// Add table rows
foreach ($rows as $r) {
    $cost = number_format($r['cost'], 2);
    $qty = $r['quantity'];
    $total = number_format($r['total'], 2);
    $grandTotal += $r['total'];

    $html .= "
    <tr>
        <td>{$r['service_name']}</td>
        <td align='right'>₦$cost</td>
        <td align='center'>$qty</td>
        <td align='right'>₦$total</td>
    </tr>";
}

$html .= "
<tr class='total-row'>
    <td colspan='3' align='right'>Grand Total</td>
    <td align='right'>₦" . number_format($grandTotal, 2) . "</td>
</tr>
</tbody>
</table>

<div class='footer'>
    Generated by Hospital Billing System on $currentDate
</div>
";

// Render PDF
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output("Invoice_$patient_name.pdf", 'I');

// Mark bills as printed
$update = $pdo->prepare("UPDATE hos_bills SET printed = 1 WHERE patient_id = ? AND printed = 0");
$update->execute([$patient_id]);
?>
